import { StyleSheet } from 'react-native';
import { colors } from '../../../theme/colors';

export const styles = StyleSheet.create({
  backdrop: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.75)',
    justifyContent: 'flex-end',
  },
  sheet: {
    backgroundColor: colors.cardDark,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    maxHeight: '92%',
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 28,
    borderWidth: 1,
    borderColor: colors.borderDark,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 12,
  },
  dragHandle: {
    width: 40,
    height: 4.5,
    borderRadius: 3,
    backgroundColor: '#475569',
    alignSelf: 'center',
    marginBottom: 12,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 14,
  },
  titleBox: {
    flex: 1,
    marginRight: 10,
  },
  modalTitle: {
    color: colors.textDark,
    fontSize: 18,
    fontWeight: '800',
  },
  modalSub: {
    color: colors.textMuted,
    fontSize: 12,
    marginTop: 2,
  },
  body: {
    marginBottom: 10,
  },
  sectionLabel: {
    color: colors.textMuted,
    fontSize: 10.5,
    fontWeight: '800',
    letterSpacing: 0.5,
    marginTop: 12,
    marginBottom: 6,
  },
  input: {
    backgroundColor: colors.surfaceDark,
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 10,
    color: colors.textDark,
    fontSize: 14,
    borderWidth: 1,
    borderColor: colors.borderDark,
  },
  disabledInputBox: {
    backgroundColor: 'rgba(15, 23, 42, 0.6)',
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  disabledInputText: {
    color: colors.textMuted,
    fontSize: 15,
    fontWeight: '700',
  },
  lockedBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(245, 158, 11, 0.15)',
    borderRadius: 6,
    paddingHorizontal: 8,
    paddingVertical: 3,
    gap: 4,
    borderWidth: 1,
    borderColor: 'rgba(245, 158, 11, 0.3)',
  },
  lockedBadgeText: {
    color: '#F59E0B',
    fontSize: 10.5,
    fontWeight: '700',
  },
  amountRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.surfaceDark,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.borderDark,
    paddingHorizontal: 14,
  },
  currency: {
    color: colors.primary,
    fontSize: 20,
    fontWeight: '800',
    marginRight: 6,
  },
  amountInput: {
    flex: 1,
    color: colors.textDark,
    fontSize: 18,
    fontWeight: '700',
    paddingVertical: 8,
  },
  metaCard: {
    backgroundColor: colors.surfaceDark,
    borderRadius: 12,
    padding: 12,
    marginTop: 12,
    borderWidth: 1,
    borderColor: colors.borderDark,
    gap: 6,
  },
  metaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  metaKey: {
    color: colors.textMuted,
    fontSize: 11.5,
    fontWeight: '600',
  },
  metaVal: {
    color: colors.textDark,
    fontSize: 11.5,
    fontWeight: '700',
  },
  auditSection: {
    marginTop: 18,
    paddingTop: 14,
    borderTopWidth: 1,
    borderTopColor: colors.borderDark,
  },
  auditHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 10,
  },
  auditTitle: {
    color: colors.textDark,
    fontSize: 13.5,
    fontWeight: '800',
  },
  auditList: {
    maxHeight: 180,
    backgroundColor: colors.surfaceDark,
    borderRadius: 12,
    padding: 10,
    borderWidth: 1,
    borderColor: colors.borderDark,
  },
  auditItem: {
    paddingVertical: 7,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 255, 255, 0.05)',
  },
  auditItemTop: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  auditActor: {
    color: '#38BDF8',
    fontSize: 12,
    fontWeight: '700',
  },
  auditTime: {
    color: colors.textDim,
    fontSize: 10.5,
  },
  auditAction: {
    color: colors.textDark,
    fontSize: 11.5,
    marginTop: 2,
  },
  submitBtn: {
    backgroundColor: colors.primary,
    borderRadius: 14,
    paddingVertical: 13,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 16,
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.35,
    shadowRadius: 8,
    elevation: 6,
  },
  submitText: {
    color: colors.white,
    fontSize: 14.5,
    fontWeight: '800',
    letterSpacing: 0.3,
  },
});
