import { StyleSheet } from 'react-native';
import { colors } from '../../../theme/colors';

export const styles = StyleSheet.create({
  container: {
    marginVertical: 6,
  },
  label: {
    color: colors.textMuted,
    fontSize: 10.5,
    fontWeight: '800',
    letterSpacing: 0.5,
    marginBottom: 6,
  },
  requiredStar: {
    color: colors.primary || '#FF385C',
  },
  triggerBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: colors.surfaceDark,
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 11,
    borderWidth: 1,
    borderColor: colors.borderDark,
  },
  triggerBtnEmpty: {
    borderColor: 'rgba(255, 56, 92, 0.4)',
  },
  triggerBtnDisabled: {
    opacity: 0.85,
    backgroundColor: 'rgba(30, 41, 59, 0.4)',
    borderColor: colors.borderDark,
  },
  triggerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flex: 1,
  },
  selectedBadge: {
    width: 26,
    height: 26,
    borderRadius: 7,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255, 56, 92, 0.15)',
  },
  selectedText: {
    color: colors.textDark,
    fontSize: 13,
    fontWeight: '700',
  },
  placeholderText: {
    color: colors.textDim,
    fontSize: 13,
    fontWeight: '500',
  },
  disabledBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: 'rgba(245, 158, 11, 0.12)',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: 'rgba(245, 158, 11, 0.25)',
  },
  disabledBadgeText: {
    color: '#F59E0B',
    fontSize: 11,
    fontWeight: '600',
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.75)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 16,
  },
  modalCard: {
    backgroundColor: colors.cardDark,
    borderRadius: 20,
    padding: 18,
    width: '100%',
    maxWidth: 350,
    borderWidth: 1,
    borderColor: colors.borderDark,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.35,
    shadowRadius: 10,
    elevation: 12,
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  modalTitle: {
    color: colors.textDark,
    fontSize: 15,
    fontWeight: '800',
  },
  quickPillsRow: {
    flexDirection: 'row',
    gap: 6,
    marginBottom: 14,
  },
  quickPill: {
    flex: 1,
    paddingVertical: 7,
    borderRadius: 8,
    backgroundColor: colors.surfaceDark,
    borderWidth: 1,
    borderColor: colors.borderDark,
    alignItems: 'center',
    justifyContent: 'center',
  },
  quickPillActive: {
    backgroundColor: 'rgba(255, 56, 92, 0.15)',
    borderColor: colors.primary,
  },
  quickPillText: {
    color: colors.textMuted,
    fontSize: 11,
    fontWeight: '600',
  },
  quickPillTextActive: {
    color: colors.primary,
    fontWeight: '700',
  },
  monthNavRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 10,
    paddingHorizontal: 4,
  },
  navBtn: {
    width: 30,
    height: 30,
    borderRadius: 8,
    backgroundColor: colors.surfaceDark,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: colors.borderDark,
  },
  monthLabel: {
    color: colors.textDark,
    fontSize: 13.5,
    fontWeight: '700',
  },
  daysHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 6,
    paddingHorizontal: 4,
  },
  dayHeaderCell: {
    width: 38,
    textAlign: 'center',
    color: colors.textDim,
    fontSize: 11,
    fontWeight: '700',
  },
  daysGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'flex-start',
    paddingHorizontal: 2,
  },
  dayCell: {
    width: 42,
    height: 38,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    marginVertical: 2,
  },
  dayCellSelected: {
    backgroundColor: colors.primary,
  },
  dayCellToday: {
    borderWidth: 1,
    borderColor: colors.primary,
  },
  dayText: {
    color: colors.textDark,
    fontSize: 12.5,
    fontWeight: '600',
  },
  dayTextSelected: {
    color: colors.white,
    fontWeight: '800',
  },
  dayTextToday: {
    color: colors.primary,
    fontWeight: '700',
  },
  dayCellEmpty: {
    width: 42,
    height: 38,
    marginVertical: 2,
  },
  webInputContainer: {
    marginTop: 10,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: colors.borderDark,
    alignItems: 'center',
  },
  webInputLabel: {
    color: colors.textMuted,
    fontSize: 11,
    marginBottom: 4,
  },
});
